### PR TITLE
(Re-submitted) Allow a file's/folder's permissions to be set (read, write, execute)

### PR DESCRIPTION
**Pull request by clayellis**
Based on what I learned from https://en.wikipedia.org/wiki/File_system_permissions

### CODE REVIEW

**Comment by rob-nash** [comment]
This is awesome! *cough @JohnSundell

**Comment by clayellis** [comment]
@rob-nash thanks!

**Review by maximkrouk — APPROVED** [review]
Pretty nice feature
> _Now I just noticed that I github allows external users to approve PRs in public repos, so the approve is just a little test for me_ 😅

**Comment by clayellis** [comment]
Closing, since it's been a few years without activity.

**Pull request closed without merging**
