### PR TITLE
Add missing tests to allTests

### PR DESCRIPTION
**Pull request by LarsJK**

### CODE REVIEW

**Comment by LarsJK** [comment]
Do the tests run an older swift version? Tested local with swift 4 in a docker container and they all passed..

**Comment by JohnSundell** [comment]
Just merged https://github.com/JohnSundell/Files/pull/28, which bumps the Swift version used for CI to 4. So try rebasing against `master` and this PR should build successfully.

**Comment by LarsJK** [comment]
Awesome. Rebased and pushed now!

**Comment by JohnSundell** [comment]
Thanks again @LarsJK 👍

**Pull request merged**
